### ISSUE TITLE
DW20 world

### ISSUE THREAD

**Issue by Spejsibu** [ModdedMinecraftClub/issue-tracker#122] opened 2022-12-14 19:04 UTC
Please, can you take a second look at the world you uploaded. Not working

**Comment by merx3d** [comment] 2022-12-14 22:18
Checking it now

**Comment by Spejsibu** [comment] 2022-12-15 22:40
And it's working?

**Comment by merx3d** [comment] 2022-12-18 20:38
So, it's a product of whatever was causing the slow startups on the server. I've been trying to diagnose it but I can't pinpoint an exact cause at the moment.

**Comment by Spejsibu** [comment] 2022-12-18 22:23
Okey, I will wait

**Comment by Spejsibu** [comment] 2022-12-18 22:26
Maybe (if will be easier for you) delete everything and sent me only basic world with my buildings, because I dont need anything else I think :)

**Comment by Spejsibu** [comment] 2022-12-29 14:30
How many time it takes yet? Please tell

**Comment by merx3d** [comment] 2023-09-30 15:57
I'm sorry Spej, I haven't been able to figure out a way to sufficiently modify the files to ensure a quick boot on launching the world. The pause is related to some mod causing a hang that eventually self resolves after a period of time once the world loads. Anytime we've gotten a stacktrace it has never yielded actionable or useful information for identifying the cause.

**Comment by Spejsibu** [comment] 2023-09-30 15:59
Okey thank you for information :)

**Comment by merx3d** [comment] 2024-11-08 03:34
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!

**Closed** 2024-11-08 03:42 UTC
Labels: Direwolf20 1.18
